version: '3'

services:
  yatb:
    build:
      dockerfile: Dockerfile.production
      context: .
    command: "--log-level=warning --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips *"
    # command: "--log-level=warning --host 0.0.0.0 --port 80"
    restart: always
    volumes:
      - ./yatb_production.env:/usr/src/yatb.env:ro
      - ./file_db.db:/usr/src/file_db.db
      - ./logs:/usr/src/logs

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./app/view/static/:/usr/static/
      - ./nginx/yatb.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    