version: "3"

services:
  yatb:
    build:
      dockerfile: Dockerfile.production
      context: .
    command: "--workers=4 --bind=0.0.0.0:80 --forwarded-allow-ips='*'"
    #  --log-level=warning --host 0.0.0.0 --port 80 --proxy-headers --forwarded-allow-ips *"
    # command: "--log-level=warning --host 0.0.0.0 --port 80"
    restart: always
    volumes:
      - ./yatb.env:/usr/src/yatb.env:ro
      - ./logs:/usr/src/logs
    environment:
      - "MONGO=mongodb://root:root@mongo:27017"
    depends_on:
      - mongo
    expose:
      - 80

  mongo:
    image: mongo:7.0
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
    volumes:
      - "yatb_data:/data/db"
    expose:
      - 27017

  caddy:
    image: caddy:2.7
    restart: always
    volumes:
      - "./app/view/static/:/usr/caddy/static/:ro"
      - "./nginx/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy_data:/data"
    ports:
      - "127.0.0.1:8080:80"

  # nginx:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./app/view/static/:/usr/static/
  #     - ./nginx/yatb.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "127.0.0.1:8080:80"

volumes:
  yatb_data:
  caddy_data:
