site_name: YATB
site_description: YATB - yet another fast and furious jeopardy-CTF taskboard
site_url: https://kksctf.github.io/yatb

repo_name: kksctf/yatb
repo_url: https://github.com/kksctf/yatb
edit_uri: ""

plugins:
  - search

nav:
  - YATB: index.md
  - config.md
  - Hacking:
      - hacking/index.md
  - release-notes.md

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - mdx_truly_sane_lists
