site_name: YATB
site_description: YATB documentation for task authors and competition organizers
site_url: https://kksctf.github.io/yatb

repo_name: kksctf/yatb
repo_url: https://github.com/kksctf/yatb
edit_uri: ""

plugins:
  - search

nav:
  - YATB: index.md
  - Task files: tasks.md
  - Release notes: release-notes.md
  - Archive:
      - Overview: old/index.md
      - Configuration: old/config.md
      - Hacking: old/hacking/index.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - mdx_truly_sane_lists
