FROM python:3.11

WORKDIR /usr/src

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install "uvicorn[standard]" gunicorn

COPY ./app ./app
COPY ./main.py .

# /usr/local/bin/uvicorn
ENTRYPOINT [ "python3", "-m", "gunicorn", "main:app", "--worker-class=uvicorn.workers.UvicornWorker"]
CMD ["--workers=1", "--log-level=warning", "--bind=0.0.0.0:80"]
