FROM python:3.12-slim AS builder
# COPY --from=ghcr.io/astral-sh/uv:0.8.19 /uv /uvx /bin/
COPY --from=ghcr.io/astral-sh/uv:0.7 /uv /uvx /bin/

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --no-editable --extra prod

ADD LICENSE README.md /app
ADD src /app/src

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-editable --extra prod

FROM python:3.12-slim

# Copy the environment, but not the source code
COPY --from=builder --chown=app:app /app/.venv /app/.venv

ENTRYPOINT ["/app/.venv/bin/python3", "-m", "gunicorn", "yatb.app:app", "--worker-class=uvicorn.workers.UvicornWorker"]
CMD ["--workers=1", "--log-level=warning", "--bind=0.0.0.0:80"]
